# Generated by Django 3.2.9 on 2021-11-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id_agenda', models.AutoField(db_column='ID_Agenda', primary_key=True, serialize=False)),
                ('data_ag', models.DateTimeField(blank=True, db_column='Data_AG', null=True, verbose_name='Data de Agendamento')),
                ('horario_ag', models.DateTimeField(blank=True, db_column='Horario_AG', null=True, verbose_name='Horario de Agendamento')),
            ],
            options={
                'db_table': 'agenda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id_contato', models.AutoField(db_column='ID_Contato', primary_key=True, serialize=False)),
                ('tel_fixo', models.IntegerField(blank=True, null=True, verbose_name='Numero do Telefone Fixo')),
                ('celular', models.IntegerField(blank=True, db_column='Celular', null=True, verbose_name='Numero do Celular')),
                ('tel_comercial', models.IntegerField(blank=True, db_column='Tel_comercial', null=True, verbose_name='Numero do Telefone Comercial')),
                ('tel_conhecidos', models.IntegerField(blank=True, db_column='Tel_Conhecidos', null=True, verbose_name='Contato de Conhecidos')),
            ],
            options={
                'db_table': 'contato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dependente',
            fields=[
                ('id_dependente', models.AutoField(db_column='ID_Dependente', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=30, null=True, verbose_name='Nome do Dependente')),
                ('sobrenome', models.CharField(blank=True, db_column='Sobrenome', max_length=30, null=True, verbose_name='Sobrenome do Dependente')),
                ('sexo', models.CharField(blank=True, db_column='Sexo', max_length=1, null=True, verbose_name='Sexo(Gênero)')),
                ('data_nascimento', models.DateTimeField(blank=True, db_column='Data_Nascimento', null=True, verbose_name='Data de Nascimento')),
                ('idade', models.TextField(blank=True, db_column='Idade', null=True, verbose_name='Idade do Dependente')),
                ('relacionamento', models.CharField(blank=True, db_column='Relacionamento', max_length=10, null=True, verbose_name='Grau de Relacionamento')),
            ],
            options={
                'db_table': 'dependente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id_endereço', models.AutoField(db_column='ID_Endereço', primary_key=True, serialize=False)),
                ('rua', models.CharField(blank=True, db_column='Rua', max_length=30, null=True, verbose_name='Nome da Rua')),
                ('numero', models.IntegerField(blank=True, db_column='Numero', null=True, verbose_name='Numero da Casa')),
                ('bairro', models.CharField(blank=True, db_column='Bairro', max_length=30, null=True, verbose_name='Bairro')),
                ('cep', models.IntegerField(blank=True, db_column='CEP', null=True, verbose_name='CEP')),
                ('cidade', models.CharField(blank=True, db_column='Cidade', max_length=20, null=True, verbose_name='Cidade')),
                ('estado_uf', models.CharField(blank=True, db_column='Estado_UF', max_length=2, null=True, verbose_name='Estado(UF)')),
                ('país', models.CharField(blank=True, db_column='País', max_length=10, null=True, verbose_name='País')),
            ],
            options={
                'db_table': 'endereco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnderecoUbs',
            fields=[
                ('id_endereço', models.AutoField(db_column='ID_Endereþo', primary_key=True, serialize=False)),
                ('rua', models.CharField(blank=True, db_column='Rua', max_length=30, null=True, verbose_name='Rua da UBS')),
                ('numero', models.IntegerField(blank=True, db_column='Numero', null=True, verbose_name='Número')),
                ('bairro', models.CharField(blank=True, db_column='Bairro', max_length=30, null=True, verbose_name='Bairro')),
                ('cep', models.IntegerField(blank=True, db_column='CEP', null=True, verbose_name='CEP')),
                ('cidade', models.CharField(blank=True, db_column='Cidade', max_length=20, null=True, verbose_name='Cidade')),
                ('estado_uf', models.CharField(blank=True, db_column='Estado_UF', max_length=2, null=True, verbose_name='Estado(UF)')),
                ('país', models.CharField(blank=True, db_column='País', max_length=20, null=True, verbose_name='País')),
            ],
            options={
                'db_table': 'endereco_ubs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id_especialidade', models.AutoField(db_column='ID_Especialidade', primary_key=True, serialize=False)),
                ('nome_especialidade', models.CharField(blank=True, db_column='Nome_Especialidade', max_length=20, null=True, verbose_name='Especialidade do Profissional')),
                ('sobrenome', models.CharField(blank=True, db_column='Sobrenome', max_length=20, null=True)),
            ],
            options={
                'db_table': 'especialidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Filiacao',
            fields=[
                ('id_filiacao', models.AutoField(db_column='ID_Filiacao', primary_key=True, serialize=False)),
                ('nome_pai', models.CharField(blank=True, db_column='Nome_Pai', max_length=10, null=True, verbose_name='Nome do Pai')),
                ('sobrenome_pai', models.CharField(blank=True, db_column='Sobrenome_Pai', max_length=20, null=True, verbose_name='Sobrenome do Pai')),
                ('nome_mae', models.CharField(blank=True, db_column='Nome_Mae', max_length=10, null=True, verbose_name='Nome da Mãe')),
                ('sobrenome_mae', models.CharField(blank=True, db_column='Sobrenome_Mae', max_length=20, null=True, verbose_name='Sobrenome da Mãe')),
            ],
            options={
                'db_table': 'filiacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicoUbs',
            fields=[
                ('id_medico', models.AutoField(db_column='ID_Medico', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=10, null=True, verbose_name='Nome do Médico')),
                ('sobrenome', models.CharField(blank=True, db_column='Sobrenome', max_length=20, null=True, verbose_name='Sobrenome do Médico')),
                ('email', models.CharField(blank=True, db_column='Email', max_length=50, null=True, verbose_name='E-mail')),
            ],
            options={
                'db_table': 'medico_ubs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_cadastro', models.AutoField(db_column='ID_Cadastro', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=30, verbose_name='Nome do Paciente')),
                ('sobrenome', models.CharField(db_column='Sobrenome', max_length=30, verbose_name='Sobrenome do Paciente')),
                ('sexo', models.CharField(blank=True, db_column='Sexo', max_length=1, null=True, verbose_name='Sexo(Gênero)')),
                ('email', models.CharField(blank=True, db_column='Email', max_length=50, null=True, verbose_name='E-mail')),
                ('rg', models.IntegerField(blank=True, db_column='RG', null=True, verbose_name='R.G.')),
                ('cartão_sus', models.IntegerField(blank=True, db_column='Cartão_SUS', null=True, verbose_name='Número do Cartão do SUS')),
                ('dt_nascimento', models.DateTimeField(blank=True, db_column='Dt_Nascimento', null=True, verbose_name='Data de Nascimento')),
                ('idade', models.IntegerField(blank=True, db_column='Idade', null=True, verbose_name='Idade do Paciente')),
                ('lactante', models.IntegerField(blank=True, db_column='Lactante', null=True, verbose_name='É Lactante?')),
                ('imagemsus', models.TextField(blank=True, db_column='imagemSUS', null=True, verbose_name='Imagem do Cartão do SUS')),
                ('imagemrg', models.TextField(blank=True, db_column='imagemRG', null=True, verbose_name='Imagem do R.G.')),
            ],
            options={
                'db_table': 'paciente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Senhas',
            fields=[
                ('id_senha', models.AutoField(db_column='ID_Senha', primary_key=True, serialize=False)),
                ('usuario', models.CharField(blank=True, db_column='Usuario', max_length=20, null=True, verbose_name='Usuário:')),
                ('senha', models.CharField(blank=True, db_column='Senha', max_length=20, null=True, verbose_name='Senha:')),
            ],
            options={
                'db_table': 'senhas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ubs',
            fields=[
                ('id_ubs', models.AutoField(db_column='ID_UBS', primary_key=True, serialize=False)),
                ('nome_unidade', models.CharField(blank=True, db_column='Nome_unidade', max_length=30, null=True, verbose_name='Nome Descritivo da Unidade')),
            ],
            options={
                'db_table': 'ubs',
                'managed': False,
            },
        ),
    ]
